### ISSUE TITLE
ns 4.01 error

### ISSUE THREAD

**Issue by p-3** [tjvantoll/nativescript-IQKeyboardManager#34]
i am getting following error with ns 4.01, works fine with ns 3.41. Do you have clue how to fix this?

node_modules/nativescript-iqkeyboardmanager/index.d.ts(13,39): error TS2552: Cannot find name 'UIBarButtonItem'. Did you mean 'IQBarButtonItem'?

node_modules/nativescript-iqkeyboardmanager/index.d.ts(19,46): error TS2304: Cannot find name 'UITraitCollection'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(21,61): error TS2304: Cannot find name 'UITraitCollection'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(21,103): error TS2552: Cannot find name 'NSObject'. Did you mean 'Object'?
node_modules/nativescript-iqkeyboardmanager/index.d.ts(23,79): error TS2304: Cannot find name 'UITraitCollection'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(23,114): error TS2304: Cannot find name 'NSArray'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(23,129): error TS2552: Cannot find name 'NSObject'. Did you mean 'Object'?
node_modules/nativescript-iqkeyboardmanager/index.d.ts(25,59): error TS2552: Cannot find name 'NSObject'. Did you mean 'Object'?

node_modules/nativescript-iqkeyboardmanager/index.d.ts(27,70): error TS2304: Cannot find name 'NSArray'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(27,85): error TS2552: Cannot find name 'NSObject'. Did you mean 'Object'?
node_modules/nativescript-iqkeyboardmanager/index.d.ts(31,15): error TS2304: Cannot find name 'NSInvocation'.
node_modules/nativescript-iqkeyboardmanager/index.d.ts(38,41): error TS2304: Cannot find name 'NSObject'.
node_modules/nativescript-iqkeyboardmanager/index.d.ts(52,45): error TS2304: Cannot find name 'NSMutableSet'.
node_modules/nativescript-iqkeyboardmanager/index.d.ts(52,65): error TS2304: Cannot find name 'NSObject'.
node_modules/nativescript-iqkeyboardmanager/index.d.ts(54,36): error TS2304: Cannot find name 'NSMutableSet'.
node_modules/nativescript-iqkeyboardmanager/index.d.ts(54,56): error TS2304: Cannot find name 'NSObject'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(56,42): error TS2304: Cannot find name 'NSMutableSet'.
node_modules/nativescript-iqkeyboardmanager/index.d.ts(56,62): error TS2304: Cannot find name 'NSObject'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(64,44): error TS2304: Cannot find name 'NSMutableSet'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(64,64): error TS2304: Cannot find name 'NSObject'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(66,35): error TS2304: Cannot find name 'NSMutableSet'.
node_modules/nativescript-iqkeyboardmanager/index.d.ts(66,55): error TS2304: Cannot find name 'NSObject'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(68,41): error TS2304: Cannot find name 'NSMutableSet'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(68,61): error TS2304: Cannot find name 'NSObject'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(70,23): error TS2304: Cannot find name 'UIKeyboardAppearance'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(82,20): error TS2304: Cannot find name 'UIFont'.
node_modules/nativescript-iqkeyboardmanager/index.d.ts(88,41): error TS2304: Cannot find name 'UITapGestureRecognizer'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(102,24): error TS2304: Cannot find name 'UIColor'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(104,34): error TS2304: Cannot find name 'UIImage'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(110,47): error TS2304: Cannot find name 'NSMutableSet'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(110,67): error TS2304: Cannot find name 'NSObject'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(112,21): error TS2304: Cannot find name 'UIColor'.
node_modules/nativescript-iqkeyboardmanager/index.d.ts(114,47): error TS2304: Cannot find name 'NSMutableSet'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(114,67): error TS2304: Cannot find name 'NSObject'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(122,105): error TS2304: Cannot find name 'NSObject'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(132,107): error TS2304: Cannot find name 'NSObject'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(137,45): error TS2503: Cannot find namespace 'interop'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(139,50): error TS2304: Cannot find name 'NSObject'.
node_modules/nativescript-iqkeyboardmanager/index.d.ts(147,31): error TS2304: Cannot find name 'UIReturnKeyType'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(149,36): error TS2304: Cannot find name 'UIViewController'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(151,30): error TS2304: Cannot find name 'UIView'.
node_modules/nativescript-iqkeyboardmanager/index.d.ts(153,35): error TS2304: Cannot find name 'UIView'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(155,38): error TS2304: Cannot find name 'UIViewController'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(157,33): error TS2304: Cannot find name 'UIView'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(159,38): error TS2304: Cannot find name 'UIView'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(171,42): error TS2304: Cannot find name 'UIView'.
node_modules/nativescript-iqkeyboardmanager/index.d.ts(177,46): error TS2304: Cannot find name 'UITraitCollection'.
node_modules/nativescript-iqkeyboardmanager/index.d.ts(179,61): error TS2304: Cannot find name 'UITraitCollection'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(179,103): error TS2304: Cannot find name 'NSObject'.
node_modules/nativescript-iqkeyboardmanager/index.d.ts(181,79): error TS2304: Cannot find name 'UITraitCollection'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(181,114): error TS2304: Cannot find name 'NSArray'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(181,129): error TS2304: Cannot find name 'NSObject'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(183,59): error TS2304: Cannot find name 'NSObject'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(185,70): error TS2304: Cannot find name 'NSArray'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(185,85): error TS2304: Cannot find name 'NSObject'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(190,34): error TS2304: Cannot find name 'UITextView'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(196,46): error TS2304: Cannot find name 'UITraitCollection'.
node_modules/nativescript-iqkeyboardmanager/index.d.ts(198,61): error TS2304: Cannot find name 'UITraitCollection'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(198,103): error TS2304: Cannot find name 'NSObject'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(200,79): error TS2304: Cannot find name 'UITraitCollection'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(200,114): error TS2304: Cannot find name 'NSArray'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(200,129): error TS2304: Cannot find name 'NSObject'.
node_modules/nativescript-iqkeyboardmanager/index.d.ts(202,59): error TS2304: Cannot find name 'NSObject'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(204,70): error TS2304: Cannot find name 'NSArray'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(204,85): error TS2304: Cannot find name 'NSObject'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(217,46): error TS2304: Cannot find name 'UITraitCollection'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(219,61): error TS2304: Cannot find name 'UITraitCollection'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(219,103): error TS2304: Cannot find name 'NSObject'.
node_modules/nativescript-iqkeyboardmanager/index.d.ts(221,79): error TS2304: Cannot find name 'UITraitCollection'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(221,114): error TS2304: Cannot find name 'NSArray'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(221,129): error TS2304: Cannot find name 'NSObject'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(223,59): error TS2304: Cannot find name 'NSObject'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(225,70): error TS2304: Cannot find name 'NSArray'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(225,85): error TS2304: Cannot find name 'NSObject'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(229,24): error TS2304: Cannot find name 'UIColor'.
node_modules/nativescript-iqkeyboardmanager/index.d.ts(231,14): error TS2304: Cannot find name 'UIFont'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(238,33): error TS2304: Cannot find name 'UIToolbar'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(238,54): error TS2304: Cannot find name 'UIInputViewAudioFeedback'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(244,46): error TS2304: Cannot find name 'UITraitCollection'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(246,61): error TS2304: Cannot find name 'UITraitCollection'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(246,103): error TS2304: Cannot find name 'NSObject'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(248,79): error TS2304: Cannot find name 'UITraitCollection'.
node_modules/nativescript-iqkeyboardmanager/index.d.ts(248,114): error TS2304: Cannot find name 'NSArray'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(248,129): error TS2304: Cannot find name 'NSObject'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(250,59): error TS2304: Cannot find name 'NSObject'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(252,70): error TS2304: Cannot find name 'NSArray'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(252,85): error TS2304: Cannot find name 'NSObject'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(274,31): error TS2304: Cannot find name 'NSObject'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(276,19): error TS2304: Cannot find name 'NSObject'.
node_modules/nativescript-iqkeyboardmanager/index.d.ts(282,32): error TS2304: Cannot find name 'NSObject'.

node_modules/nativescript-iqkeyboardmanager/index.d.ts(284,34): error TS2304: Cannot find name 'NSObject'.
